### PR TITLE
Introduce Sync API for enhanced data synchronization with Supabase

### PR DESCRIPTION
**Pull request by chrox**
This pull request introduces a Sync API to enhance data synchronization between the application and the Supabase backend. It leverages the `SyncClient` class to handle two-way incremental synchronization operations (`pushChanges` and `pullChanges`) directly with Supabase, with `last-writer-wins` approach to resolve conflicts, ensuring synchronization of user reading data such as `books`, `config`, and `notes`. Now after logging in with your account you can synchronize your reading progress on all platforms that Readest runs.

### CODE REVIEW

**Comment by molezz** [comment]
it seems the web data and windows client data dose not sync.
After login and import the same book form local disk, the client open the book as new, there is no note and progress.
web: windows edge  0.9.0
client: windows x64 0.9.0

**Comment by chrox** [comment]
The progress sync issue is hopefully fixed in released version 0.9.1. Could you try it to see if it's solved?

**Comment by molezz** [comment]
> The progress sync issue is hopefully fixed in released version 0.9.1. Could you try it to see if it's solved?

It seems partly solved. When open web, The progress recovered success. When open client, the progress didn't sync. 
And the note sync from client to web is good, but note on the web didn't sync to the open client. 

the account is gmail

**Comment by chrox** [comment]
Note that data are not synced in real-time you need to close and reopen the book to sync data. And another thing is the local time of your computer. Readest uses timestamps to decide how to merge data from different devices and newer data will override older data. So make sure your client computer has correct clock time.

**Comment by chrox** [comment]
Could you also check the network tab of the inspector in your client app by right clicking the page and selecting inspect elements? After refreshing the page you will see the sync API calls with url: web.readest.com/api/sync. Does it have errors for the api calls?

**Comment by molezz** [comment]
the web all 200
```
https://web.readest.com/api/sync?since=1736215352926&type=notes&book=07e8940d5a7a1c8feb6746b49a885061
Request Method:
GET
200 OK
``` 


the windows client had some 204 

image
```
https://web.readest.com/api/sync?since=1736215352926&type=notes&book=07e8940d5a7a1c8feb6746b49a885061
Request Method:
OPTIONS
204 No Content
```

**Comment by molezz** [comment]
PS： there sync between different win client is good， I will use client instead web before android release now~

**Comment by chrox** [comment]
Thanks for the information. I will check on that.

**Comment by jueinin** [comment]
Hi @chrox , I want to ask you, what is your Supabase table creation statement? This thing doesn't seem to create tables automatically during project initialization. I want to use my own Supabase account.
and this link is hard code https://github.com/readest/readest/blob/c009edca6122994bd991a0780cde9b3fec393d8d/apps/readest-app/src/services/constants.ts#L290  make it harder to selfhost

**Comment by chrox** [comment]
> 
> 
> Hi @chrox , I want to ask you, what is your Supabase table creation statement? This thing doesn't seem to create tables automatically during project initialization. I want to use my own Supabase account.
> 
> and this link is hard code https://github.com/readest/readest/blob/c009edca6122994bd991a0780cde9b3fec393d8d/apps/readest-app/src/services/constants.ts#L290  make it harder to selfhost

There is a wiki page on this: https://github.com/readest/readest/wiki/Supabase-Tables-Schema-for-Sync-API

**Comment by chrox** [comment]
Welcome to send a PR to make this configurable.

**Pull request merged**
